### PR TITLE
[Bug]Support YOLOv8-cls

### PR DESCRIPTION
**Pull request by wjj19950828**
# Create A Good Pull Request

> 下面的文字请保留在PR说明的最后面，并在提完PR后，根据实际情况勾选确认以下情况  

Please check the follow step before merging this pull request

- [x] Python code style verification
- [x] Review all the code diff by yourself
- [ ] All models(TensorFLow/Caffe/ONNX/PyTorch) testing passed
- [x] Details about your pull request, releated issues

If this PR add new model support, please update `model_zoo.md` and add model to out test model zoos(@wjj19950828)
- [x] New Model Supported
- [ ] No New Model Supported

## Do follow contribution
- Support YOLOv8-cls
- soloved https://github.com/PaddlePaddle/X2Paddle/issues/948

### CODE REVIEW

**Comment by glenn-jocher** [comment]
@wjj19950828 thank you for working on this! Let me know if you need any help from the YOLOv8 team.

**Comment by glenn-jocher** [comment]
@wjj19950828 hi there! Could you provide a status on this? 

I'd really like to enable Paddle export for YOLOv8. It's one of the only export format that's causing errors for us still:
https://github.com/ultralytics/ultralytics/actions/runs/4537845907/jobs/7996127140

Screenshot 2023-03-28 at 17 29 01

**Comment by wjj19950828** [comment]
@glenn-jocher hi～Sorry for the late reply, currently X2Paddle has released version 1.4.1, and verified that YOLOv8 cls/det/seg are all supported, thanks for the feedback~

The following commands are all supported
```shell
yolo export model=yolov8n.pt format=paddle
yolo export model=yolov8n-cls.pt format=paddle
yolo export model=yolov8n-seg.pt format=paddle
```

Looking forward to more cooperation~

**Comment by glenn-jocher** [comment]
@wjj19950828 it's great to hear that X2Paddle has released version 1.4.1 and supports YOLOv8 export to the various cls/det/seg tasks! Thank you for the bug fix, I will update our code to allow X2Paddle export to all these formats now :)

**Comment by glenn-jocher** [comment]
@wjj19950828 I confirm it works now!

Screenshot 2023-03-31 at 13 49 42

**Pull request merged**
